# Generated by Django 5.2.7 on 2025-11-04 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('minimum_qualifications', models.TextField()),
                ('class_specifications_file', models.FileField(blank=True, null=True, upload_to='job_specs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('evaluation_criteria', models.JSONField(default=dict, help_text='Structured criteria for evaluating applicants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('application_file', models.FileField(upload_to='applications/', validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf'])])),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted from application document')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='resume_screening.jobposition')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('email', 'job_position')},
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('LIKELY_QUALIFIED', 'Likely Qualified'), ('NEEDS_REVIEW', 'Needs Human Review'), ('LIKELY_NOT_QUALIFIED', 'Likely Not Qualified')], max_length=30)),
                ('confidence_score', models.FloatField(help_text='Model confidence (0-1)')),
                ('explanation', models.TextField(help_text='AI-generated explanation for the classification')),
                ('criteria_scores', models.JSONField(default=dict, help_text='Breakdown of scores for specific job criteria')),
                ('model_version', models.CharField(help_text='Version of the model used', max_length=100)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('human_reviewed', models.BooleanField(default=False)),
                ('human_decision', models.CharField(blank=True, max_length=30, null=True)),
                ('human_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_result', to='resume_screening.applicant')),
            ],
            options={
                'ordering': ['-screened_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='training_data/', validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf'])])),
                ('extracted_text', models.TextField(help_text='Extracted text from training document')),
                ('label', models.CharField(choices=[('LIKELY_QUALIFIED', 'Likely Qualified'), ('NEEDS_REVIEW', 'Needs Human Review'), ('LIKELY_NOT_QUALIFIED', 'Likely Not Qualified')], help_text='Ground truth label for training', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Include in training set')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='resume_screening.jobposition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('model_path', models.CharField(help_text='Path to saved model', max_length=500)),
                ('training_samples', models.IntegerField()),
                ('validation_accuracy', models.FloatField(blank=True, null=True)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField(default=dict, help_text='Model hyperparameters and training config')),
                ('metrics', models.JSONField(default=dict, help_text='Detailed performance metrics')),
                ('is_active', models.BooleanField(default=False, help_text='Currently deployed model')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_versions', to='resume_screening.jobposition')),
            ],
            options={
                'ordering': ['-training_date'],
                'unique_together': {('job_position', 'version')},
            },
        ),
    ]
