# Generated by Django 5.2.7 on 2025-11-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='archived',
            field=models.BooleanField(default=False, help_text='Whether this applicant has been archived'),
        ),
    ]
